apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aquasecurity.github.io/helm-charts/
    chart: trivy-operator
    targetRevision: 0.14.0   # check latest
    helm:
      releaseName: trivy-operator
      values: |
        trivy:
          ignoreUnfixed: true
        serviceMonitor:
          enabled: true
        compliance:
          enabled: true
        rbac:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
