apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: 2.33.3  # check latest: https://portainer.github.io/k8s/
    helm:
      values: |
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: portainer.rackspace.cristian.co.nz
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          enabled: true
          storageClass: ssd
          size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
