apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://schwarzit.github.io/node-red-chart/
    chart: node-red
    targetRevision: 0.35.0
    helm:
      releaseName: node-red
      values: |
        # Example values: change to suit your environment
        replicaCount: 1
        service:
          type: ClusterIP
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: node-red
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
