apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://hub.jupyter.org/helm-chart/
    chart: jupyterhub
    targetRevision: 4.3.1
    helm:
      releaseName: jupyterhub
      values: |
        # fullnameOverride and nameOverride distinguishes blank strings, null values,
        # and non-blank strings. For more details, see the configuration reference.
        fullnameOverride: ""
        nameOverride:

        enabled:

        custom: {}

        imagePullSecret:
          create: false
          automaticReferenceInjection: true

        hub:
          revisionHistoryLimit:
          config:
            JupyterHub:
              admin_access: true
              authenticator_class: dummy
          service:
            type: ClusterIP
          baseUrl: /
          db:
            type: sqlite-pvc
            pvc:
              accessModes:
                - ReadWriteOnce
              storage: 5Gi
          image:
            name: quay.io/jupyterhub/k8s-hub
            tag: "4.3.1"
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          podSecurityContext:
            runAsNonRoot: true
            fsGroup: 1000
          deploymentStrategy:
            type: Recreate

        proxy:
          deploymentStrategy:
            type: Recreate
          service:
            type: ClusterIP
          chp:
            image:
              name: quay.io/jupyterhub/configurable-http-proxy
              tag: "5.1.0"
            containerSecurityContext:
              runAsNonRoot: true
              runAsUser: 65534
              runAsGroup: 65534
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]

        singleuser:
          image:
            name: quay.io/jupyterhub/k8s-singleuser-sample
            tag: "4.3.1"
          memory:
            guarantee: 1G
          storage:
            capacity: 10Gi
          networkPolicy:
            enabled: false
          extraLabels:
            hub.jupyter.org/network-access-hub: "true"

        scheduling:
          userScheduler:
            enabled: true
            replicas: 2
            image:
              name: registry.k8s.io/kube-scheduler
              tag: "v1.30.14"

        prePuller:
          hook:
            enabled: true
            image:
              name: quay.io/jupyterhub/k8s-image-awaiter
              tag: "4.3.1"

        ingress:
          enabled: false

        cull:
          enabled: true
          users: false
          adminUsers: true
          timeout: 3600
          every: 600
          concurrency: 10

  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
