apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 7.0.1   # check latest
    helm:
      releaseName: falco
      values: |
        falco:
          grpc:
            enabled: true
          http_output:
            enabled: true
          json_output: true
          priority: notice
        falcosidekick:
          enabled: true
          config:
            webhook:
              address: "http://loki.monitoring.svc.cluster.local:3100"  # or Slack/Webhook
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
