apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeview
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://code.benco.io/kubeview/deploy/helm
    chart: kubeview
    # You may optionally specify targetRevision (chart version or app version)
    targetRevision: "2.0.6"
    helm:
      releaseName: kubeview
      values: |
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
