apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openspeedtest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://openspeedtest.github.io/Helm-chart/
    chart: openspeedtest
    targetRevision: 0.1.2 # check latest with helm search
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
