apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://alexjustesen.github.io/helm-charts
    chart: speedtest-exporter
    targetRevision: 1.5.3 # check latest with helm search
    helm:
      values: |
        image:
          repository: ghcr.io/alexjustesen/speedtest-exporter
          tag: latest
        serviceMonitor:
          enabled: true
        schedule: "0 * * * *" # runs hourly
        tolerations: []
        affinity: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
