apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.18.0  # check latest version
    helm:
      releaseName: external-dns
      values: |
        provider: cloudflare  # or route53, google, digitalocean, etc.
        domainFilters:
          - rackspace.cristian.co.nz
        txtOwnerId: "k8s-baseline"
        policy: sync
        registry: txt
        sources:
          - ingress
        interval: 1m
        logLevel: info

        # For Cloudflare
        cloudflare:
          secretName: cloudflare-api-token
          proxied: true

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
